# Generated by Django 3.2.10 on 2021-12-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_available',
            field=models.IntegerField(default=0),
        ),
    ]
